### ISSUE TITLE
> constraint does not behave as expected

### ISSUE THREAD

**Issue by DurhamSmith** [neil-lindquist/linear-programming#10]
It seems that when adding a `>` constraint the actual behavior is `>=`

E.g
```
(with-solved-problem ((max (= w (+ x (* 4 y) (* 3 z))))
                      (<= (+ (* 2 x) y) 8)
                      (<= (+ y z) 7)
                      (bounds (2 z 5))
                      (> x 3)
                      (integer x))
  (format t "Objective value solution: ~A~%" w)
  (format t "x = ~A (reduced cost: ~A)~%" x (reduced-cost x))
  (format t "y = ~A (reduced cost: ~A)~%" y (reduced-cost y))
  (format t "z = ~A (reduced cost: ~A)~%" z (reduced-cost z)))
```

Which gives 
```
Objective value solution: 26
x = 3 (reduced cost: 7)
y = 2 (reduced cost: 0)
z = 5 (reduced cost: 0)
```

**Comment by neil-lindquist** [comment]
Yes, `>` is short hand for `>=` and not a strict inequality.  Strict inequalities don't work with non-integer constraints (cf. the difference between supremum and maximum).  So, I followed the convention from other linear-programming packages that `>` denotes "greater than or equal to" and added `>=` as a more readable alias.

That was probably a poor choice on my part and I should probably deprecate `>` and `<` with a warning.
