### ISSUE TITLE
Redundand constraint leads to wrong solution

### ISSUE THREAD

**Issue by vi1** [neil-lindquist/linear-programming#11]
```
;; Gives:  
;; w=1.5   x=1.0 y=0.5,
;; but y can't be 0.5  because of (>= y 1.0)
(lp:with-solved-problem
    ((min (= w (+ x y)))
     (>= x 1.0)
     (>= y 1.0)
     ;; If the first two inequalities hold, this is redundant constraint
     ;; however, it leads to wrong solution
     #-nil (>= (+ x (* 2.0 y)) 2.0))
  (format t "w=~a   x=~a y=~a~%" w x y)
  (values))
```

The effect is like it just takes 3rd constraint and throws away 2nd.

**Comment by neil-lindquist** [comment]
Thanks for raising this.  There was a bug in the treatment of simple variable bounds like `(>= y 1.0)` that broke the Simplex solver.
I just pushed a fix to the master branch.
Otherwise, you can work around this with the old version by shifting your variables so that the lower bound is 0.

**Comment by vi1** [comment]
Thank you.
