### ISSUE TITLE
Feasible problem reported unbounded

### ISSUE THREAD

**Issue by bd339** [neil-lindquist/linear-programming#2]
Using the code from Ultralisp, the following raises an unbounded problem condition:

`(with-input-from-string (in "((MIN (+ (* 0.6861807 A) (* 1 B))) (>= (+ (* 1 B) (* 0.6861807 A)) 0.9372585) (>= (+ (* 1 B) (* 0.7776901 A)) 0.7461006) (>= (+ (* 1 B) (* 0.14247864 A)) 0.38555977))")
	   (lp:solve-problem (lp:read-sexp in)))`

That should not be possible (due to the way the problem is constructed). Here's an optimal solution found by LPSolve that I have checked is correct.

`a=1.01470781626246
b=0.240985580341555`

Am I using the API wrong or is this a bug?

**Comment by neil-lindquist** [comment]
Sorry for the delay, I never got a notification for this issue.

This is a bug.  There are a few checks that test equality against 0, which causes issues in the presence of round off error.  Rationals should work exactly, and I'll try to get this fixed.

Thanks for bringing it to my attention.

**Comment by neil-lindquist** [comment]
I think I have this fixed in the master branch (and thus Ultralisp).  Let me know if it's still occuring
