### ISSUE TITLE
Supporting GLPK

### ISSUE THREAD

**Issue by phikal** [neil-lindquist/linear-programming#5]
Hi, the README mentions

> If there is interest in a high performance backend, please open an issue; the library is setup to support a high performance backend, but there has yet to be any interest in it.

and I'd like to say that I'd be interested in it, and helping to get it done. A while ago, I was playing with [cl-glpk](https://github.com/phikal/cl-glpk-1), and got it working to some degree, so I suppose that implementing a GLPK backend for this library would go along the same lines.

**Comment by neil-lindquist** [comment]
Glancing at cl-glpk and it's high level API, it shouldn't be too hard to reuse code from that library to do the heavy lifting.  The one complication I'm seeing is that glpk is licensed under GPL.  I'm unsure whether it can be worked around by putting all of the glpk dependent code in a single, GPL-licensed file, or if that code will need its own repository.

For implementing this, it should just be a matter of getting the low-level bindings in place, then mapping this library's API/data representation to the low-level bindings.

**Comment by phikal** [comment]
Oh, I didn't see that this repository was published under the MIT license. The main value that cl-glpk has to offer is that the ffi is already implemented, but that's not something that can be replicated (the "official" version isn't up to date anyway).

Would you be interested in adding this to the repository, if I could make it work?

**Comment by neil-lindquist** [comment]
After thinking about things (and a little feedback on StackExchange), I think the best way to do this is to put the glpk related code into a separate repository so that it's clear to the user what is and isn't under the GPL.

I'm happy to create the repository and work with you there on it, unless you would rather create and maintain such a repo yourself?

**Comment by phikal** [comment]
I'm glad to help, but I don't think my CL is good enough to maintain a project.

**Comment by neil-lindquist** [comment]
I created an initial repo at https://github.com/neil-lindquist/linear-programming-glpk
It's just the basic file structure that will be (probably) needed, plus the ffi wrappers from [sellout/cl-glpk](https://github.com/sellout/cl-glpk).  I figure your fixes can be added along when ffi.lisp is checked against glpk.h for any other issues.
I've also added issues for specific tasks to that repo.

**Comment by neil-lindquist** [comment]
I've gotten the GLPK backend implemented to the point where it can solve basic problems.  I'm going to close this issue in favor of opening new, individual issues on that repo.
