### ISSUE TITLE
Feasible integer problem reported as unbounded

### ISSUE THREAD

**Issue by bd339** [neil-lindquist/linear-programming#8]
Thank you for fixing #7 , but now a slightly larger problem fails (for a different reason):
```LISP
(lp:with-solved-problem 
	     ((MAX (= W (+ (* 1 FUEL))))
	      (INTEGER PSHF T65 FUEL T63 HKGWZ T66 GPVTF T68 QDVJ T64 KHKGT T69 XJWVT T67
		       DCFZ T62 NZVS T61 ORE)
	      (LINEAR-PROGRAMMING/PROBLEM:BOUNDS (0 ORE 1000000000000)) (= (+ (* -1 PSHF) (* 7 T65)) 0)
	      (= (+ (* -1 FUEL) (* 1 T63)) 0) (= (+ (* -1 HKGWZ) (* 5 T66)) 0)
	      (= (+ (* -1 GPVTF) (* 2 T68)) 0) (= (+ (* -1 QDVJ) (* 9 T64)) 0)
	      (= (+ (* -1 KHKGT) (* 8 T69)) 0) (= (+ (* -1 XJWVT) (* 2 T67)) 0)
	      (= (+ (* -1 DCFZ) (* 6 T62)) 0) (= (+ (* -1 NZVS) (* 5 T61)) 0)
	      (<=
	       (+ (* -1 PSHF) (* 8 T17) (* 7 T20) (* 10 T22) (* 8 T26) (* 7 T29) (* 10 T31)
		  (* 8 T64) (* 7 T67) (* 10 T69))
	       0)
	      (<=
	       (+ (* -1 HKGWZ) (* 48 T16) (* 12 T17) (* 5 T22) (* 48 T25) (* 12 T26)
		  (* 5 T31) (* 48 T63) (* 12 T64) (* 5 T69))
	       0)
	      (<=
	       (+ (* -1 GPVTF) (* 9 T16) (* 1 T17) (* 9 T25) (* 1 T26) (* 9 T63) (* 1 T64))
	       0)
	      (<= (+ (* -1 QDVJ) (* 1 T16) (* 1 T25) (* 1 T63)) 0)
	      (<= (+ (* -1 KHKGT) (* 5 T16) (* 5 T25) (* 5 T63)) 0)
	      (<= (+ (* -1 XJWVT) (* 44 T16) (* 44 T25) (* 44 T63)) 0)
	      (<=
	       (+ (* -1 DCFZ) (* 7 T20) (* 3 T22) (* 7 T29) (* 3 T31) (* 7 T67) (* 3 T69))
	       0)
	      (<=
	       (+ (* -1 NZVS) (* 29 T16) (* 7 T22) (* 29 T25) (* 7 T31) (* 29 T63)
		  (* 7 T69))
	       0)
	      (<=
	       (+ (* -1 ORE) (* 10 T1) (* 1 T2) (* 9 T7) (* 8 T8) (* 7 T9) (* 157 T14)
		  (* 165 T15) (* 179 T18) (* 177 T19) (* 165 T21) (* 157 T23) (* 165 T24)
		  (* 179 T27) (* 177 T28) (* 165 T30) (* 139 T36) (* 144 T37) (* 145 T40)
		  (* 176 T43) (* 171 T44) (* 114 T46) (* 189 T53) (* 121 T58) (* 157 T61)
		  (* 165 T62) (* 179 T65) (* 177 T66) (* 165 T68))
	       0))
	   w)
```
This raises an UNBOUNDED-PROBLEM-ERROR but only with the default Simplex backend. GLPK backend works as intended (w = 82892753).

**Comment by neil-lindquist** [comment]
I've fixed the unbounded error; although, it now fails to find an optimal solution before running out of memory.
I'm guessing GLPK uses some advanced tricks to cut down the search space more effectively and know when a solution is effectively optimal.

I don't know what your end use is, but I'm guessing you could likely skip the integer constraints and just round to the nearest integer before you use them.  The values of `w ORE HKGWZ GPVTF QDVJ KHKGT XJWVT DCFZ NZVS PSHF` are `8.289275e7 1.0e12 4.3484155e9 7.5524506e8 8.289275e7 4.1446378e8 3.6472812e9 1.2920908e10 2.7665457e9 1.3357246e10`, so you'd be introducing an error less than `00.001%` to those variables.

**Comment by bd339** [comment]
Great! I haven't had the chance to try it yet but it's not a big problem. I already got the solution from GLPK and it was very much a one-off kind of thing. I only opened these bugs to improve the quality of the implementation :)
GLPK found the solution in 0.1 secs. But it does mean that this library probably is not that practical for integer programming for me. Some of my ILPs even choke GLPK and I have to use a commercial solver.

**Comment by neil-lindquist** [comment]
Good to hear that this wasn't hindering you.  And the issues have exposed some embarrassing holes in the test suite, so I really appreciate them.

Yea, this library isn't well tuned for large/hard problems.
Adding a CPLEX or Gurobi backend shouldn't be too hard, I just haven't made it enough of a priority.
