### ISSUE TITLE
Error while parsing arguments to MACROLET REDUCED-COST

### ISSUE THREAD

**Issue by realdea8** [neil-lindquist/linear-programming#9]
In the README.md example, the WITH-SOLUTION-VARIABLES and WITH-SOLVED-PROBLEM macros give an error while parsing arguments to macrolet REDUCED-COST.

Using the WITH-SOLVED-PROBLEM example:

```lisp
(with-solved-problem ((max (= w (+ x (* 4 y) (* 3 z))))
                      (<= (+ (* 2 x) y) 8)
                      (<= (+ y z) 7))
  (format t "Objective value solution: ~A~%" w)
  (format t "x = ~A (reduced cost: ~A)~%" x (reduced-cost solution 'x))
  (format t "y = ~A (reduced cost: ~A)~%" y (reduced-cost solution 'y))
  (format t "z = ~A (reduced cost: ~A)~%" z (reduced-cost solution 'z)))
```
produces the following error:

> Execution of a form compiled with errors.
> Form:
>   (REDUCED-COST SOLUTION 'X)
> Compile-time error:
>   during macroexpansion of (REDUCED-COST SOLUTION 'X). Use *BREAK-ON-SIGNALS* to
> intercept.
> 
>  error while parsing arguments to MACROLET REDUCED-COST:
>    too many elements in
>      (SOLUTION 'X)
>    to satisfy lambda list
>      (LINEAR-PROGRAMMING/SOLVER::VAR):
>    exactly 1 expected, but got 2
>    [Condition of type SB-INT:COMPILED-PROGRAM-ERROR]
> 
> Restarts:
>  0: [RETRY] Retry SLIME REPL evaluation request.
>  1: [*ABORT] Return to SLIME's top level.
>  2: [ABORT] abort thread (#<THREAD "new-repl-thread" RUNNING {10005D7533}>)
> 
> Backtrace:
>   0: ((LAMBDA ()))
>   1: (SB-INT:SIMPLE-EVAL-IN-LEXENV (WITH-SOLVED-PROBLEM ((MAX #) (<= # 8) (<= # 7)) (FORMAT T "Objective value solution: ~A~%" W) (FORMAT T "x = ~A (reduced cost: ~A)~%" X (REDUCED-COST SOLUTION #)) (FORMA..
>   2: (EVAL (WITH-SOLVED-PROBLEM ((MAX #) (<= # 8) (<= # 7)) (FORMAT T "Objective value solution: ~A~%" W) (FORMAT T "x = ~A (reduced cost: ~A)~%" X (REDUCED-COST SOLUTION #)) (FORMAT T "y = ~A (reduced cos..
>   3: (SWANK::EVAL-REGION "(with-solved-problem ((max (= w (+ x (* 4 y) (* 3 z)))) ..)
>   4: ((LAMBDA NIL :IN SWANK-REPL::REPL-EVAL))
>   5: (SWANK-REPL::TRACK-PACKAGE #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {100296D8CB}>)
>   6: (SWANK::CALL-WITH-RETRY-RESTART "Retry SLIME REPL evaluation request." #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {100296D86B}>)
>   7: (SWANK::CALL-WITH-BUFFER-SYNTAX NIL #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {100296D84B}>)
>   8: (SWANK-REPL::REPL-EVAL "(with-solved-problem ((max (= w (+ x (* 4 y) (* 3 z)))) ..)
>   9: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SWANK-REPL:LISTENER-EVAL "(with-solved-problem ((max (= w (+ x (* 4 y) (* 3 z)))) ..)
>  10: (EVAL (SWANK-REPL:LISTENER-EVAL "(with-solved-problem ((max (= w (+ x (* 4 y) (* 3 z)))) ..)
>  11: (SWANK:EVAL-FOR-EMACS (SWANK-REPL:LISTENER-EVAL "(with-solved-problem ((max (= w (+ x (* 4 y) (* 3 z)))) ..)
>  12: (SWANK::PROCESS-REQUESTS NIL)
>  13: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
>  14: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
>  15: (SWANK/SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SWANK::HANDLE-REQUESTS) {1001B4008B}>)
>  16: ((FLET SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "/home/sernamar/.emacs.d/elpa/slime-2.26.1/swank/sbcl.lisp") #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SWANK::HANDLE-REQUESTS) {1..
>  17: (SWANK::CALL-WITH-BINDINGS ((*STANDARD-INPUT* . #<SWANK/GRAY::SLIME-INPUT-STREAM {1001C06123}>)) #<CLOSURE (LAMBDA NIL :IN SWANK::HANDLE-REQUESTS) {1001B400AB}>)
>  18: (SWANK::HANDLE-REQUESTS #<SWANK::MULTITHREADED-CONNECTION {1004CC64C3}> NIL)
>  19: ((FLET SB-UNIX::BODY :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
>  20: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
>  21: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
>  22: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
>  23: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFA3F95ED6B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
>  24: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "new-repl-thread" RUNNING {10005D7533}> NIL #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::SPAWN-REPL-THREAD) {10005D74DB}> NIL)
>  25: ("foreign function: call_into_lisp")
>  26: ("foreign function: new_thread_trampoline")

I've taken a look at the code at:

https://github.com/neil-lindquist/linear-programming/blob/2f1dc9c7386aefe5241857b05095cfa69d52636e/src/solver.lisp#L92-L111

and it seems that the macrolet REDUCE-COST expects a single variable. So the following code will work as expected:

```lisp
(with-solved-problem ((max (= w (+ x (* 4 y) (* 3 z))))
                      (<= (+ (* 2 x) y) 8)
                      (<= (+ y z) 7))
  (format t "Objective value solution: ~A~%" w)
  (format t "x = ~A (reduced cost: ~A)~%" x (reduced-cost x))
  (format t "y = ~A (reduced cost: ~A)~%" y (reduced-cost y))
  (format t "z = ~A (reduced cost: ~A)~%" z (reduced-cost z)))
```

**Comment by neil-lindquist** [comment]
Thank you for bringing this to my attention.  I apparently mixed it up with `solution-reduced-cost`.

The example section in the README now all works.

**Comment by realdea8** [comment]
Great. Thanks!
